import type { Metadata } from "next";
import './globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-[100vh] relative select-none overflow-hidden lg:overflow-auto">
          <div className="w-full h-[100vh] bg-[url('/bg-image.jpg')] bg-cover absolute blur-lg -z-20"></div>
          <div className="absolute bg-[rgba(19,52,88,0.89)] z w-full h-[100vh] select-none -z-10 flex justify-center">
            <div className="xl:w-[1056px] 2xl:w-[1320px] border border-[#294969] flex relative">
              <div className="absolute xl:ml-[336px] 2xl:ml-[420px] h-full border-l border-[#294969]"></div>
              <div className="absolute xl:ml-[672px] 2xl:ml-[840px] h-full border-l border-[#294969]"></div>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
