import type { Metadata } from "next";
import './globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-[100vh] relative">
          <div className="w-full h-[100vh] bg-[url('/bg-image.jpg')] bg-cover absolute blur-lg -z-20"></div>
          <div className="absolute bg-[rgba(19,52,88,0.89)] z w-full h-[100vh] select-none -z-10"></div>
          {children}
        </div>
      </body>
    </html>
  );
}
